# Generated by Django 3.2.8 on 2021-12-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_categories', models.CharField(choices=[('General Office Supplies', 'General Office Supplies'), ('Field logistics', 'Field logistics'), ('toiletries', 'toiletries')], max_length=200, null=True)),
                ('company_name', models.TextField()),
                ('email_address', models.EmailField(max_length=254)),
                ('country', models.CharField(choices=[('Ghana', 'Ghana'), ('Nigeria', 'Nigeria'), ('Togo', 'Togo')], max_length=200, null=True)),
                ('local_area', models.TextField()),
                ('type_of_firm', models.CharField(choices=[('Limited Liability', 'Limited Liability'), ('Partnership', 'Partnership'), ('Sole Proprietorship', 'Sole Proprietorship')], max_length=200, null=True)),
                ('date_of_registration', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
