# Generated by Django 3.2.8 on 2021-12-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_categories', models.CharField(choices=[('Management Consultancy', 'Management Consultancy'), ('Individual Consultancy', 'Individual Consultancy')], max_length=200, null=True)),
                ('company_name', models.TextField()),
                ('email_address', models.EmailField(max_length=254)),
                ('country', models.CharField(choices=[('Ghana', 'Ghana'), ('Nigeria', 'Nigeria'), ('Togo', 'Togo')], max_length=200, null=True)),
                ('local_area', models.TextField()),
                ('type_of_firm', models.CharField(choices=[('Limited Liability', 'Limited Liability'), ('Partnership', 'Partnership'), ('Sole Proprietorship', 'Sole Proprietorship')], max_length=200, null=True)),
                ('date_of_registration', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nonconsultancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_categories', models.CharField(choices=[('Security Service', 'Security Service'), ('Cleaning Service', 'Cleaning Service')], max_length=200, null=True)),
                ('company_name', models.TextField()),
                ('email_address', models.EmailField(max_length=254)),
                ('country', models.CharField(choices=[('Ghana', 'Ghana'), ('Nigeria', 'Nigeria'), ('Togo', 'Togo')], max_length=200, null=True)),
                ('local_area', models.TextField()),
                ('type_of_firm', models.CharField(choices=[('Limited Liability', 'Limited Liability'), ('Partnership', 'Partnership'), ('Sole Proprietorship', 'Sole Proprietorship')], max_length=200, null=True)),
                ('date_of_registration', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
