# Generated by Django 3.2.8 on 2022-01-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerinfo',
            name='contact2',
            field=models.IntegerField(default='0000000'),
        ),
    ]
