# Generated by Django 3.2.8 on 2022-02-09 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vdms', '0002_consultant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultant',
            name='date_of_registration',
        ),
    ]
