# Generated by Django 3.2.8 on 2022-01-17 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vdms', '0002_providerinfo_contact2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerinfo',
            name='contact2',
        ),
    ]
