# Generated by Django 3.2.8 on 2022-01-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdms', '0003_remove_providerinfo_contact2'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerinfo',
            name='altcontact',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='providerinfo',
            name='altemail_address',
            field=models.EmailField(default='example@mail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='providerinfo',
            name='classification',
            field=models.TextField(default='xxxxxx'),
        ),
        migrations.AddField(
            model_name='providerinfo',
            name='postal_address',
            field=models.TextField(default='Accra Ghana'),
        ),
    ]
