# Generated by Django 3.2.8 on 2022-02-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdms', '0003_remove_consultant_date_of_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultant',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='consultant',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
