# Generated by Django 3.2.8 on 2022-02-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdms', '0004_auto_20220209_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendemail',
            name='attachment',
            field=models.FileField(default='000', upload_to='files'),
        ),
    ]
