# Generated by Django 3.2.8 on 2022-01-19 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vdms', '0004_auto_20220119_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='company_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vdms.providerinfo'),
        ),
        migrations.AlterField(
            model_name='providerinfo',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vdms.category'),
        ),
        migrations.AlterField(
            model_name='providerinfo',
            name='sub_categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vdms.subcategory'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vdms.category'),
        ),
    ]
