# Generated by Django 3.2.8 on 2022-02-10 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vdms', '0008_alter_sendemail_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultant',
            name='subcategory',
        ),
    ]
