# Generated by Django 3.2.8 on 2022-02-11 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vdms', '0009_remove_consultant_subcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SendEmail',
        ),
    ]
