# Generated by Django 3.2.8 on 2022-02-11 19:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdms', '0019_alter_sendemail_receipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendemail',
            name='bcc',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=254), size=None), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='sendemail',
            name='cc',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=254), size=None), blank=True, size=None),
        ),
    ]
