# Generated by Django 3.2.8 on 2022-02-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdms', '0021_auto_20220214_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerinfo',
            name='classification',
            field=models.TextField(blank=True, default='xxxxxx'),
        ),
    ]
