# Generated by Django 3.2.8 on 2022-02-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdms', '0022_alter_providerinfo_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
